### ISSUE TITLE
S3RequestMiddleware runtime error with invalid URL strings

### ISSUE THREAD

**Issue by hishma** [swift-aws/aws-sdk-swift#189] opened 2019-10-23 18:44 UTC
**Describe the bug**

It looks like `virtualAddressFixup(_request:)`in `S3RequestMiddleware` generates a runtime error if the string that is parsed from the request.url is not a valid URL string.

**To Reproduce**

```swift
import S3 //ensure this module is specified as a dependency in your package.swift
import NIO

let bucket = "my-bucket"

let key = "hello world.txt" // <-- Note the space!

let s3 = S3(
    accessKeyId: "Your-Access-Key",
    secretAccessKey: "Your-Secret-Key",
    region: .uswest2
)

// Create Bucket, Put an Object, Get the Object
let createBucketRequest = S3.CreateBucketRequest(bucket: bucket)

s3.createBucket(createBucketRequest).then { response -> Future<S3.PutObjectOutput> in
    // Upload text file to the s3
    let bodyData = "hello world".data(using: .utf8)!
    let putObjectRequest = S3.PutObjectRequest(acl: .publicRead, bucket: bucket, contentLength: Int64(bodyData.count), body: bodyData, key: key)
    return s3.putObject(putObjectRequest)
}.then { response -> Future<S3.GetObjectOutput> in
    let getObjectRequest = S3.GetObjectRequest(bucket: bucket, key: key)
    return s3.getObject(getObjectRequest)
}.whenSuccess { response in
    if let body = response.body {
        print(String(data: body, encoding: .utf8))
    }
}
```

**Expected behavior**

The S3RequestMiddleware should throw, instead of generating a runtime error.

**Setup (please complete the following information):**
 - OS: MacOS 10.5
 - Version of aws-sdk-swift:  0.5.0
 - Authentication mechanis:  hard-coded credentials

**Additional context**

It seems like keys with space should be valid as why are when using S3 generally. But I think thats probably a separate issue?

I currently work around this by URL encoding the key.

**Comment by adam-fowler** [comment] 2019-10-24 06:25
This looks like it caused by the conversion from URL to String and back. The percent encoded spaces are lost when converting from URL to String

**Comment by adam-fowler** [comment] 2019-11-10 10:05
fixed on master

**Closed by adam-fowler** 2019-11-10 10:05 UTC
Labels: bug
