### ISSUE TITLE
ApiGateway.RestApi.binaryMediaTypes become nil

### ISSUE THREAD

**Issue by noppoMan** [swift-aws/aws-sdk-swift#33] opened 2017-05-20 18:14 UTC
binaryMediaTypes property in api response seems String Type

**Comment by adam-fowler** [comment] 2019-07-12 10:03
Don't know if this occurs on other services but when an array only has one element it seems that ApiGateway outputs it as ```"element"``` instead of ```["element"]```

**Comment by adam-fowler** [comment] 2019-08-07 07:04
fixed in https://github.com/swift-aws/aws-sdk-swift-core/pull/103

**Closed by adam-fowler** 2019-08-07 07:04 UTC
Labels: bug

**Comment by adam-fowler** [comment] 2019-12-12 10:10
Found the cause of this. The hal+json reports an array with a single value just as the value. But multiple values as an array.
